NOMBRE: IASS
categoria: BUSINESS_STAT
grupos_consultas:
  "Series originales de los \xEDndices de cifra de negocio":
    consultas:
    - '6525'
    id: '1'
  "\xCDndices de VAB":
    consultas:
    - '6530'
    id: '3'
  "\xCDndices de empleo":
    consultas:
    - '6528'
    id: '2'
metadatos_subtitle:
  '6525': ''
  '6528': ''
  '6530': ''
metadatos_title:
  '6525': "Series originales de los \xEDndices de cifra de negocio"
  '6528': "\xCDndices de empleo"
  '6530': "\xCDndices de VAB"
periodicidad:
  '6525':
    frecuencia: Mensual
    validFrom: '2005-01-01'
    validTo: '2022-08-31'
  '6528':
    frecuencia: Mensual
    validFrom: '2005-01-01'
    validTo: '2022-08-31'
  '6530':
    frecuencia: (Mensual)
    validFrom: '2005-01-01'
    validTo: '2022-08-31'
subcategoria: Indicadores de Actividad del Sector Servicios
variables:
- IASS_TIPOVENTAS
- TERRITORIO
