NOMBRE: IASS
categoria: BUSINESS_STAT
subcategoria: Indicadores de Actividad del Sector Servicios
grupos_consultas:
  Series originales de los índices de cifra de negocio:
    id: '1'
    consultas:
    - '6525'
  Índices de empleo:
    id: '2'
    consultas:
    - '6528'
  Índices de VAB:
    id: '3'
    consultas:
    - '6530'
variables:
- IASS_TIPOVENTAS
- TERRITORIO
metadatos_title:
  '6525': Series originales de los índices de cifra de negocio
  '6528': Índices de empleo
  '6530': Índices de VAB
metadatos_subtitle:
  '6525': ''
  '6528': ''
  '6530': ''
