NOMBRE: AE
categoria: POP_MIGRATION
subcategoria: Andaluces en el Exterior
grupos_consultas:
  Andaluces residentes en el resto de España:
    id: '1'
    consultas:
    - '437'
  Andaluces Residentes en el Resto de España:
    id: '2'
    consultas:
    - '439'
  Andaluces residentes en el resto del mundo:
    id: '3'
    consultas:
    - '454'
    - '455'
    - '1915'
  Población residente en el resto del mundo:
    id: '4'
    consultas:
    - '1917'
variables:
- SEXO
- TERRITORIO
- LUGARNACIMIEN
- EDAD
- TERRITORIO_1
- ARE_INSCRIPCION
metadatos_title:
  '437': Andaluces residentes en el resto de España
  '439': Andaluces Residentes en el Resto de España
  '454': Andaluces residentes en el resto del mundo
  '455': Andaluces residentes en el resto del mundo
  '1915': Andaluces residentes en el resto del mundo
  '1917': Población residente en el resto del mundo
metadatos_subtitle:
  '437': Andaluces residentes en el resto de España por comunidad autónoma de residencia
    y provincia de nacimiento según sexo *
  '439': Andaluces residentes en el resto de España por grupos de edad y provincia
    de nacimiento según sexo *
  '454': Población inscrita en Andalucía por provincia de inscripción y lugar de nacimiento
    según sexo *
  '455': Población inscrita en Andalucía por continente/país de residencia, lugar
    de nacimiento según provincia de inscripción y sexo *
  '1915': Población nacida en Andalucía por provincia de nacimiento y lugar de inscripción
    según sexo *
  '1917': Nuevas inscripciones por lugar de inscripción * y lugar de nacimiento según
    sexo **
