NOMBRE: AE
categoria: POP_MIGRATION
grupos_consultas:
  "Andaluces Residentes en el Resto de Espa\xF1a":
    consultas:
    - '439'
    id: '2'
  "Andaluces residentes en el resto de Espa\xF1a":
    consultas:
    - '437'
    id: '1'
  Andaluces residentes en el resto del mundo:
    consultas:
    - '454'
    - '455'
    - '1915'
    id: '3'
  "Poblaci\xF3n residente en el resto del mundo":
    consultas:
    - '1917'
    id: '4'
metadatos_subtitle:
  '1915': "Poblaci\xF3n nacida en Andaluc\xEDa por provincia de nacimiento y lugar\
    \ de inscripci\xF3n seg\xFAn sexo *"
  '1917': "Nuevas inscripciones por lugar de inscripci\xF3n * y lugar de nacimiento\
    \ seg\xFAn sexo **"
  '437': "Andaluces residentes en el resto de Espa\xF1a por comunidad aut\xF3noma\
    \ de residencia y provincia de nacimiento seg\xFAn sexo *"
  '439': "Andaluces residentes en el resto de Espa\xF1a por grupos de edad y provincia\
    \ de nacimiento seg\xFAn sexo *"
  '454': "Poblaci\xF3n inscrita en Andaluc\xEDa por provincia de inscripci\xF3n y\
    \ lugar de nacimiento seg\xFAn sexo *"
  '455': "Poblaci\xF3n inscrita en Andaluc\xEDa por continente/pa\xEDs de residencia,\
    \ lugar de nacimiento seg\xFAn provincia de inscripci\xF3n y sexo *"
metadatos_title:
  '1915': Andaluces residentes en el resto del mundo
  '1917': "Poblaci\xF3n residente en el resto del mundo"
  '437': "Andaluces residentes en el resto de Espa\xF1a"
  '439': "Andaluces Residentes en el Resto de Espa\xF1a"
  '454': Andaluces residentes en el resto del mundo
  '455': Andaluces residentes en el resto del mundo
periodicidad:
  '1915':
    frecuencia: Anual
    validFrom: '2009-01-01'
    validTo: '2022-12-31'
  '1917':
    frecuencia: Anual
    validFrom: '2016-01-01'
    validTo: '2022-12-31'
  '437':
    frecuencia: Anual
    validFrom: '1998-01-01'
    validTo: '2021-12-31'
  '439':
    frecuencia: Anual
    validFrom: '1998-01-01'
    validTo: '2021-12-31'
  '454':
    frecuencia: Anual
    validFrom: '2009-01-01'
    validTo: '2022-12-31'
  '455':
    frecuencia: Anual
    validFrom: '2009-01-01'
    validTo: '2022-12-31'
subcategoria: Andaluces en el Exterior
variables:
- SEXO
- TERRITORIO
- LUGARNACIMIEN
- EDAD
- TERRITORIO_1
- ARE_INSCRIPCION
